# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 061a0edf8c536cc62c950c3c474fbdadfe29eb1b2e78287fceb053e8748810c10724064fa46a7009b8a776d2d5c454419488be4fbd93fec14ec49ad1bcc42cb8

test:
  secret_key_base: a22793d0739f998d4c3e83a38111a956549ef4c1d0b1f163533c16350b48a3895514fdce4aad478d63432bc2bc22d9523b76b19679fd8fff24c47cefd4613be3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
